name: .NET Build xx IR

on:
  push:
    branches: [ bleed ]
  workflow_dispatch:

permissions:
  contents: read


jobs:
  build:
    env:
      IR_API_URL: "https://app.dev.invisirisk.com"
    runs-on: ubuntu-latest
    name: Run build
    steps:     
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: ${{env.IR_API_URL}}
          app_token: ${{secrets.IR_API_KEY_DEV}}
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100-rc.2.24474.11
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develop
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
